from django.conf.urls import url
from . import views, auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^manage$', views.manage, name='manage'),
    url(r'^manage_staff$', views.manage_staff, name='manage_staff'),
    url(r'^manage_robot$', views.manage_robot, name='manage_robot'),
    url(r'^manage_answer$', views.manage_answer, name='manage_answer'),
    url(r'^preview$', views.preview, name='preview'),
    url(r'^chat_([1-9][0-9]*)$', views.chat, name='chat'),
    url(r'^m_chat_([1-9][0-9]*)$', views.m_chat, name='m_chat'),
    url(r'^manage_answer/add$', views.add_answer, name='add_answer'),
    url(r'^manage_answer/delete/([1-9][0-9]*)$', views.delete_answer, name='delete_answer'),
    url(r'^manage_answer/modify/([1-9][0-9]*)$', views.modify_answer, name='modify_answer'),
    url(r'^manage_robot/add$', views.add_response, name='add_response'),
    url(r'^manage_robot/delete/([1-9][0-9]*)$', views.delete_response, name='delete_response'),
    url(r'^manage_robot/modify/([1-9][0-9]*)$', views.modify_response, name='modify_response'),
    url(r'^manage_FAQ$', views.set_faq, name='set_faq'),
    url(r'^manage_FAQ/up/([1-9][0-9]*)$', views.up_question, name='up_question'),
    url(r'^manage_FAQ/down/([1-9][0-9]*)$', views.down_question, name='down_question'),
    url(r'^manage_FAQ/add/([1-9][0-9]*)$', views.add_question, name='add_question'),
    url(r'^manage_FAQ/delete/([1-9][0-9]*)$', views.delete_question, name='delete_question'),
    url(r'^manage_FAQ/company$', views.modify_faq_to_company, name='modify_faq_to_company'),
    url(r'^manage_FAQ/robot$', views.modify_faq_to_robot, name='modify_faq_to_robot'),
    url(r'^verification/expire$', views.verification_expire, name='verification_expire'),
    url(r'^staff_base$', views.staff_base, name='staff_base'),
    url(r'^staff_chat$', views.staff_chat, name='staff_chat'),
    url(r'^toolbar_chat_([1-9][0-9]*)$', views.toolbar_chat, name='toolbar_chat'),
    url(r'^example/([1-9][0-9]{4})$', views.example_company, name='example_company'),
    url(r'^chatting_graph$', views.chatting_graph, name='chatting_graph'),
    url(r'^todays_graph$', views.todays_graph, name='todays_graph'),
    url(r'^area_graph$', views.area_graph, name='area_graph'),
    url(r'^image_send', views.image_send, name='image_send'),
    url(r'^send_image$', views.send_image, name='send_image'),

    #auth
    url(r'^login_company$', auth_views.login_company, name='login_company'),
    url(r'^login_staff$', auth_views.login_staff, name='login_staff'),
    url(r'^authenticate_company$', auth_views.authenticate_company, name='authenticate_company'),
    url(r'^authenticate_staff$', auth_views.authenticate_staff, name='authenticate_staff'),
    url(r'^signup$', auth_views.signup, name='signup'),
    url(r'^signup/submit$', auth_views.signup_submit, name='signup_submit'),
    url(r'^logout$', auth_views.logout, name='logout'),
    url(r'^manage_staff/add$', auth_views.add_staff, name='add_staff'),
    url(r'^manage_staff/delete/([1-9][0-9]*)$', auth_views.delete_staff, name='delete_staff'),
    url(r'^manage_staff/modify/([1-9][0-9]*)$', auth_views.modify_staff, name='modify_staff'),
    url(r'^self_information$', auth_views.self_information, name="self_information"),
    url(r'^company_information$', auth_views.company_information, name="company_information"),
    url(r'^modify_password$', auth_views.modify_password, name="modify_password"),
    url(r'^verification/([0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})$',
        auth_views.validate_user, name='verification'),
    url(r'^success$', auth_views.verification_success, name="verification_success"),
    url(r'^fail$', auth_views.verification_fail, name="verification_fail"),
    url(r'^forget_password1$', auth_views.forget_password1, name="forget_password1"),
    url(r'^forget_password2$', auth_views.forget_password2, name="forget_password2"),
    url(r'^forget_password3$', auth_views.forget_password3, name="forget_password3"),
    url(r'^forget_password4$', auth_views.forget_password4, name="forget_password4"),
    url(r'^modify_image$', auth_views.modify_image, name="modify_image"),
    url(r'^modify_status_to_true$', auth_views.modify_status_to_true, name='modify_status_to_true'),
    url(r'^modify_status_to_out$', auth_views.modify_status_to_out, name='modify_status_to_out'),
    url(r'^staff_detail$', auth_views.detail, name='staff_detail'),
    url(r'^modify_company_information$', auth_views.modify_company_information, name='modify_company_information'),
    url(r'^modify_nickname$', auth_views.modify_nickname, name='modify_nickname'),
]
